### PR TITLE
Add captions and alt text to images in index doc

### PR DESCRIPTION
**Pull request by willingc**
I love the new screenshots :smile:

I've added accessibility alt-txt and captions to the images on the index page to provide the reader more context when first reading the doc.

### CODE REVIEW

**Comment by willingc** [comment]
Closes #168

**Comment by minrk** [comment]
Great! A couple of questions:

- I see you switched from image to figure. Is there a reason for the change (so I can know the right thing to use in the future)?
- The screenshots also show up in cli.rst and merging.rst, were you going to update those, as well?

**Comment by willingc** [comment]
With rst, you would use `figure` if you wish to add a caption. `image` doesn't offer that. Typically, I use `image` and only use `figure` when I wish to add a caption. [Reference](http://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html#images-and-figures)

I wasn't sure if we wanted captions in `cli.rst` or `merging.rst` since the images reflected the subsection where in `index.rst` I felt the captions helped reinforce the text. Happy to add if desired.

**Comment by willingc** [comment]
Probably would be helpful to add the alt-text to the images in `cli.rst` and `merging.rst`. I'll add that in a separate PR.

**Pull request merged**
