### PR TITLE
Add jupyter lab extension

### PR DESCRIPTION
**Pull request by vidartf**
Builds on the server extension in #297, and adds a jupyter lab extension.

### CODE REVIEW

**Comment by vidartf** [comment]
Future improvement suggestions:
 - [ ] Add action to diff two notebooks (dialog with two filebrowsers?)
 - [ ] Use better icons + style them similarly to existing NB toolbar icons.

These should not be in this PR though.

**Comment by Analect** [comment]
@vidartf ... is this in a working state to use against jupyterlab 0.27?
If I have an external service on jupyterhub running nbdime, can it use that, or does it end up installing nbdime as part of the extension installation?  Tks.

**Comment by vidartf** [comment]
@Analect I cannot guarantee anything about this, but hope to work further on it this month. I did have a working version at some point though, so if you play around with it, you might be able to get it working.

Note: Even after getting the classic notebook extension into master, we might still hold off on this until the relevant jupyterlab APIs reach version 1.0. This would be in order to reduce our own maintenance burden in order to stay compatible with latest JL version.

**Comment by Analect** [comment]
Thanks for the update @vidartf 
To what extent would this extension interact with the [jupyterlab-git](https://github.com/jupyterlab/jupyterlab-git/issues/163) one?
I know you worked a little with @zzhangjii at JupyterCon on this, and was wondering how you were thinking about the integration of the two ... if at all.

**Comment by vidartf** [comment]
@Analect The solution that was agreed and implemented there is for jupyterlab-git to expose a function for diff providers to register themselves. Nbdime would then check on load whether jupyterlab-git is present, and if so, register itself.

**Comment by vidartf** [comment]
This will likely stay as a PR until various jupyterlab APIs stabilize (tip 1.0), in order to reduce maintenance burden of following JL releases.

**Comment by elgalu** [comment]
is it stable enough now?

**Comment by vidartf** [comment]
The extension is still dependent on the following jupyterlab extensions that have not reached a 1.0:
```
@jupyterlab/application
@jupyterlab/apputils
@jupyterlab/docregistry
@jupyterlab/codeeditor
@jupyterlab/codemirror
@jupyterlab/notebook
@jupyterlab/outputarea
@jupyterlab/rendermime
```
This means that for every minor release of those packages, we would have to release a new version of the nbdime lab extension. Hopefully that will not happen too often, but at least I want to wait until https://github.com/jupyterlab/jupyterlab/pull/3608 is included in lab to minimize installation troubleshooting.

**Pull request merged**
