### PR TITLE
Fix drag and drop

### LINKED ISSUE #721: CM6 tail: Merge view cell drag and drop
After the CM6 rewrite, the drag-and-drop of cells in the merge view is no longer working:

image

The highlighted handles are meant to allow users to re-order cells in the merge. Outputs were also re-orderable, but I haven't checked the behavior on master for this.

### PR DESCRIPTION
**Pull request by fcollonval**
Fixes #721

It also at least partly addresses https://github.com/jupyter/nbdime/issues/720 as it restores Lumino widgets styling

---

- This switches from phosphor convention to lumino convention for CSS and events naming
- Fix the position of the drag image  
  @krassowski I was surprised to have to add `.lm-mod-drag-image { left: 0px; top: 0px; }`. Is there something to fix upstream or did I missed something?

### CODE REVIEW

**Comment by fcollonval** [comment]
bot please update snapshots

**Comment by fcollonval** [comment]
bot please update playwright snapshots

**Comment by fcollonval** [comment]
bot please update playwright snapshots

**Comment by fcollonval** [comment]
bot please update snapshots

**Comment by krassowski** [comment]
> @krassowski I was surprised to have to add .lm-mod-drag-image { left: 0px; top: 0px; }. Is there something to fix upstream or did I missed something?

I tested it locally and compared with lab/notebook. It seems we should add it in lumino as default; it is not strictly needed in lab nor notebook because the only other children of body are fully positioned and do not take up any space.

**Comment by krassowski** [comment]
I opened https://github.com/jupyterlab/lumino/pull/651. For now I think we can merge this as-is, all worked well locally.

**Review by krassowski — APPROVED** [review]
Thanks!

**Pull request merged**
