### PR TITLE
Add translation for the frontend in Lab

### PR DESCRIPTION
**Pull request by fcollonval**
Plug in the translation infrastructure of JupyterLab for the frontends.

### CODE REVIEW

**Comment by krassowski** [comment]
Some untranslated strings I noticed from using the labextension:

- [ ] image
    https://github.com/jupyter/nbdime/blob/f044d232c0a2f64a711c8d18dbd090934d20524a/packages/nbdime/src/diff/model/notebook.ts#L41
   (note: in the diff mode, it is fine in the merge mode)
- [ ] image
   https://github.com/jupyter/nbdime/blob/f044d232c0a2f64a711c8d18dbd090934d20524a/packages/nbdime/src/common/mergeview.ts#L468
- [ ] image
   `Hide unchanged cells` is in the HTML template, so I guess we need to override it in diff and merge around here:
   https://github.com/jupyter/nbdime/blob/f044d232c0a2f64a711c8d18dbd090934d20524a/packages/webapp/src/app/diff.ts#L258-L261
  https://github.com/jupyter/nbdime/blob/f044d232c0a2f64a711c8d18dbd090934d20524a/packages/webapp/src/app/compare.ts#L203-L206
   https://github.com/jupyter/nbdime/blob/f044d232c0a2f64a711c8d18dbd090934d20524a/packages/webapp/src/app/merge.ts#L446-L449
- [ ] ` unchanged cell(s) hidden`, well this is defined in CSS and therefore not accessible
     image
- [ ] Lab commands:
   image
   https://github.com/jupyter/nbdime/blob/f044d232c0a2f64a711c8d18dbd090934d20524a/packages/labextension/src/plugin.ts#L199-L200
    https://github.com/jupyter/nbdime/blob/f044d232c0a2f64a711c8d18dbd090934d20524a/packages/labextension/src/plugin.ts#L224-L227
- [ ] Server missing message
  https://github.com/jupyter/nbdime/blob/f044d232c0a2f64a711c8d18dbd090934d20524a/packages/labextension/src/plugin.ts#L38-L39

**Comment by fcollonval** [comment]
Thanks Mike for looking at those

As you mentioned, some will be hard to solve like the one using the CSS `content` for hidden cells. And I'm uncomfortable to translate the `collapsibleHeader` as it is defined in the model - I prefer the translation to occur only in views. But I could probably go ahead as changing the code logic will be too large.

**Comment by fcollonval** [comment]
Thanks @krassowski after 6ccc4cc the element remaining in Lab is the _unchanged cells_ as it is set in the CSS. The web apps template are also not covered as anyway it will require quite some work to add server support for handling the mo/json files.

**Comment by krassowski** [comment]
Thanks! I moved the remaining bits to https://github.com/jupyter/nbdime/issues/724#issue-1961931353.

The snapshots will need updating after the italics were removed. I would recommend merging with main to pickup https://github.com/jupyter/nbdime/pull/714 that I just merged to facilitate.

**Comment by fcollonval** [comment]
bot please update playwright snapshots

**Comment by fcollonval** [comment]
Kicking the CI

**Comment by krassowski** [comment]
Seems only Windows snapshots were updated: 
bot please update playwright snapshots

**Review by krassowski — APPROVED** [review]
Thanks @fcollonval!

**Pull request merged**
