### PR TITLE
support base-url

### LINKED ISSUE #244: building the webapp to expose the preliminary api as a service
@vidartf 
I may be jumping the gun here, but is there a basic dockerfile available that will install and then run the nbdime [webapp](https://github.com/jupyter/nbdime/blob/master/nbdime/webapp/nbdimeserver.py).

I manually installed a dev version, following [this](https://nbdime.readthedocs.io/en/latest/installing.html#installing-latest-development-version) and then tried running `python nbdime/webapp/nbdimeserver.py -p 8888`, but wasn't able to get anything running.  Maybe this is still a WIP.

I was experimenting around getting a number of 'services' running under jupyterhub, using kubernetes and wanted to add nbdime as a service in order to potentially be able to access its [API](https://nbdime.readthedocs.io/en/latest/restapi.html).  Is this viable to do, as yet?

Thanks.

### PR DESCRIPTION
**Pull request by minrk**
Resolves #244 .

TODO:

- [x] make sure base_url is supported in every web application
- [x] prefix URLs with base_url in typescript
- [x] run tests with base URL, e.g. `a%20b` to ensure double-escapes don't happen

### CODE REVIEW

**Comment by vidartf** [comment]
Should be ready for review now.

**Comment by minrk** [comment]
When I do nbdiff-web, `browse` tries to connect to port 0 instead of the selected port.

**Comment by Analect** [comment]
@minrk 
Thanks for your efforts on this.
I took the liberty of installing nbdime from your base_url branch and testing it again in the context of running as an external service in jupyterhub, running on kubernetes.

image

The service starts OK ... although I'm not sure if I should be feeding a different `base_url` to the default `/` one.  My url on jupyterhub is `jupyterhub.myserver.com/services/nbdime/`.   

Below are the logs from jupyterhub, which look OK, in terms the hub acknowledging the two services I have (nbviewer an nbdime).

image

However, I'm still getting a `404`, as per below.
image

Just to troubleshoot a little further, I ended up forwarding port 9000 from my kubernetes cluster to `localhost:9000`.  I then tried to enter two versions of the same notebook (I assume you enter it as `raw`?).

`https://raw.githubusercontent.com/jupyter/notebook/4671bb9cb7252d52fcf82e3fae727f4a1ca4e6a7/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb`

`https://raw.githubusercontent.com/jupyter/notebook/1b51230e8ba5164a7b92d7dea79cf27d26ae78cb/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb`

The browser console shows a `Diff request failed` and other CORS-related issues.
image

I'd love to get this running.  Any thoughts on what parts of the puzzle I might still be missing?  Thanks.

**Comment by vidartf** [comment]
@Analect Working on this as we speak, when its working we'll merge it into master

**Comment by vidartf** [comment]
@minrk: Hopefully everything is working now :)

**Comment by Analect** [comment]
@vidartf 
Thanks.  Let me know if you need me to test anything.  Regards.

**Comment by Analect** [comment]
@vidartf 

Tried this again after your last commit ... and the port-forwarding described above now works, which is great.  However, I still need some guidance in getting this somehow passed through to the jupyterhub endpoint `../services/nbdime/` .. which is, as yet, not working.

image

**Comment by minrk** [comment]
Almost working. Just needs a few tweaks:

- baseUrl is losing one character when joining
- clicking the compare button is stripping the base URL

**Comment by vidartf** [comment]
There were some other issues as well, c.f. newly pushed commits :)

**Comment by minrk** [comment]
It works!

@Analect you can run nbdime as a JupyterHub service with:

```python
c.JupyterHub.services = [
    {
        'name': 'nbdime',
        'url': 'http://127.0.0.1:9999',
        'command': [sys.executable, '-m', 'nbdime.webapp.nbdimeserver', '--port=9999', '--base-url=/services/nbdime/'],
        'cwd': '/path/to/notebooks',
    },
]
```

**Comment by Analect** [comment]
@minrk 
Just a quick question ref. this.  The jupyterhub config above is for running nbdime as a 'managed service'.  Is that correct?  Up to now, I've been running nbdime in a separate 'pod', so just wondering if it's possible to run as an 'external service' too?  As per docs in nbviewer, I think leaving out the `command` parameter delineates it as an external service.  Is that the case here too?

Also, just so I understand:  when `cwd: /path/to/notebooks` is set, in the context of a jupyterhub set-up, what path should this ideally point at.  In the case of a 'managed' service, will this be pointing at a path on the jupyterhub container?  In the case of an 'external' service, it would be a path in the nbdime container?

Is there a way, using the jupyter content API to point at or load notebooks that may be in a users' (ie. a user for which a notebook server has been spawned from the hub) `/home/jovyan/notebooks` folder?

Sorry for the series of questions, but just looking to fill in gaps I still have in how this should work in the context of Jupyterhub.

Thanks again both of you for your work on this.

**Comment by Analect** [comment]
@minrk 
Just a heads-up that I got this working as an external service.  I hadn't previously been feeding the `--base-url` parameter properly in the start-up command on the remote container.   This is the Dockerfile command I'm using to start the external nbdime service:
`CMD ["./env/bin/python3", "-m", "nbdime.webapp.nbdimeserver", "--port=9000", "--log-level=DEBUG", "--ip=0.0.0.0", "--base-url=/services/nbdime/"]` while below is the config from my `jupyerhub_config.py`.

```
{
        'name': 'nbdime',
        'url': 'http://' + os.environ['NBDIME_SERVICE_HOST'] + ':' + os.environ['NBDIME_SERVICE_PORT'],
        'admin': True,
        'api_token': os.environ['NBDIME_JHUB_TOKEN']
    }
```

I'm still interested in understanding if `cwd` in the context of an external service is referencing a folder within the container running `nbdime`.  In the context of some of the work you were doing on jupyterhub, and being able to authenticate through to hub users' files using the contents API .. is that something nbdime could viably be used for ... by having a contents API end-point to a notebook as one input to the UI below, for instance.

I'm not sure if the `Export diff` button is wired up yet.  I couldn't manage to get it to work.  Is it meant to download a file in the browser?

image

**Comment by minrk** [comment]
> Just a quick question ref. this. The jupyterhub config above is for running nbdime as a 'managed service'. Is that correct? Up to now, I've been running nbdime in a separate 'pod', so just wondering if it's possible to run as an 'external service' too? As per docs in nbviewer, I think leaving out the command parameter delineates it as an external service. Is that the case here too?

Yes, my example was as a managed service. An external service will work as well, just leave out the command in config, and pass the same command when launching it separately (you may also want to change the ip, depending on container networking.


> Also, just so I understand: when cwd: /path/to/notebooks is set, in the context of a jupyterhub set-up, what path should this ideally point at. In the case of a 'managed' service, will this be pointing at a path on the jupyterhub container? In the case of an 'external' service, it would be a path in the nbdime container?

In the managed service case, yes, it would be a path in the jupyterhub container. cwd is not meaningful when the service is external (it sets the location in which to launch the command, so doesn't do anything when the Hub doesn't launch the command).


> Is there a way, using the jupyter content API to point at or load notebooks that may be in a users' (ie. a user for which a notebook server has been spawned from the hub) /home/jovyan/notebooks folder?

Not at the moment, no. nbdime needs to get notebooks from its local disk, so it will need to have access to files within its container, such as through volume mounts.

**Comment by vidartf** [comment]
> I'm not sure if the Export diff button is wired up yet. I couldn't manage to get it to work. Is it meant to download a file in the browser?

It is supposed to work, yes. What browser are you on? Are you getting any errors in the browser console (typically available via F12 button or menu) on page load, or when clicking this button? Could you please open up a new issue with such a report?

**Comment by Analect** [comment]
@vidartf  ... I will open a separate issue.

> Not at the moment, no. nbdime needs to get notebooks from its local disk, so it will need to have access to files within its container, such as through volume mounts.

@minrk ... I'm not sure the above is strictly true ... in that it appears possible to pass notebooks as a json payload from an API to nbdime for notebooks that are located elsewhere.

So for instance, if I run ...
`http://jupyterhub.myserver.com/services/nbdime/?base=https%3A%2F%2Fraw.githubusercontent.com%2Fjupyter%2Fnotebook%2F4671bb9cb7252d52fcf82e3fae727f4a1ca4e6a7%2Fdocs%2Fsource%2Fexamples%2FNotebook%2FWhat%2520is%2520the%2520Jupyter%2520Notebook.ipynb&local=&remote=https%3A%2F%2Fraw.githubusercontent.com%2Fjupyter%2Fnotebook%2F1b51230e8ba5164a7b92d7dea79cf27d26ae78cb%2Fdocs%2Fsource%2Fexamples%2FNotebook%2FWhat%2520is%2520the%2520Jupyter%2520Notebook.ipynb`

... I can see logs on the nbdime instance performing these task.

```
017-02-20T10:30:14.675009643Z [D connectionpool:818] Starting new HTTPS connection (1): raw.githubusercontent.com
2017-02-20T10:30:14.997244111Z [D connectionpool:395] https://raw.githubusercontent.com:443 "GET /jupyter/notebook/4671bb9cb7252d52fcf82e3fae727f4a1ca4e6a7/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb HTTP/1.1" 200 2609
2017-02-20T10:30:15.025731255Z [D connectionpool:818] Starting new HTTPS connection (1): raw.githubusercontent.com
2017-02-20T10:30:15.217115929Z [D connectionpool:395] https://raw.githubusercontent.com:443 "GET /jupyter/notebook/1b51230e8ba5164a7b92d7dea79cf27d26ae78cb/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb HTTP/1.1" 200 2608
2017-02-20T10:30:15.332032010Z [I web:1971] 200 POST /services/nbdime/api/diff (10.4.6.129) 659.09ms
```

I suppose, by extension, I was just hoping to tap into notebooks running in a given notebook server session via an API call the same way.

**Pull request merged**
