### PR TITLE
Update web dependencies 

### LINKED ISSUE #406: Upgrade jupyterlab dependencies to work with jupyterlab 0.33.0
```
"nbdime-jupyterlab@0.2.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab             Extension        Package
>=0.17.2 <0.18.0       >=0.16.0 <0.17.0 @jupyterlab/apputils
>=2.0.2 <3.0.0         >=1.1.2 <2.0.0   @jupyterlab/coreutils
>=0.17.2 <0.18.0       >=0.16.0 <0.17.0 @jupyterlab/notebook
>=0.17.2 <0.18.0       >=0.16.0 <0.17.0 @jupyterlab/rendermime
>=3.0.3 <4.0.0         >=2.0.0 <3.0.0   @jupyterlab/services
```

### PR DESCRIPTION
**Pull request by vidartf**
- Updates jupyterlab/phosphor/codemirror dependencies.
- Also updates other dev dependencies, like typescript.
- Uses the improved way of getting the preferred mimetype from newest lab.
- Now compiles to ES6. Certain older browser versions do not support ES6, but I do not think those currently support nbdime anyway. Could be worth a check.

Fixes #406.

### CODE REVIEW

**Comment by vidartf** [comment]
Toggled to pick up #409, now that it has been merged.

**Comment by gnestor** [comment]
@vidartf Are you planning on publishing a new release on PyPI or npm or both?

**Comment by vidartf** [comment]
@gnestor Yes, hopefully this week!

**Comment by vidartf** [comment]
published!

**Pull request merged**
