### PR TITLE
Fix bug caused by recent version Jupyter Lab

### PR DESCRIPTION
**Pull request by deanp70**
Due to an update in JupyterLab, dev build was failing. This single line change seems to have fixed it. It was caused by the Jupyterlab/services package that has updated it's API.

This is referred to in these issues – #531 and https://github.com/jupyterlab/jupyterlab/issues/8736

Please let me know if I should do anything else for the PR to be accepted.

### CODE REVIEW

**Comment by deanp70** [comment]
Any input on this? Not sure why it's failing tests.

**Comment by vidartf** [comment]
Thanks, this looks good! I'll do a pass on issues/PRs next week, and do a "final" release for lab 2.x, and then update to work with lab 3, so I'll do the merge + fixing of CI then 👍

**Comment by deanp70** [comment]
> Thanks, this looks good! I'll do a pass on issues/PRs next week, and do a "final" release for lab 2.x, and then update to work with lab 3, so I'll do the merge + fixing of CI then 👍

Awesome. Let me know if I can help.

**Comment by fzimmermann89** [comment]
Thank you! ... Do you maybe want to tag the fixed version?

**Pull request merged**
