### PR TITLE
Support hiding base editor

### LINKED ISSUE #682: Support merge view with 3 panels (theirs | final | ours) in addition to the current 4 panels views
In `@jupyterlab/git`, the merge addon from CM5 was used directly to display merge views for plain text using a 3 panels view: `theirs | final | ours`. It will be nice to add a setting in nbdime widget to select either the current 4 panels view or that 3 panel view.

### PR DESCRIPTION
**Pull request by fcollonval**
Fixes #682

It adds a new CLI option `--no-base` to switch from a 4-panels to a 3-panels merge view.

TODO
- [x] Fix final padding not added to the merged editor

### CODE REVIEW

**Comment by fcollonval** [comment]
bot please update playwright snapshots

**Comment by HaudinFlorence** [comment]
@fcollonval In the 3 panels view ui-test, it seems that the expected number of picker markers symbols should be 26 instead of the 25 given number.

**Comment by HaudinFlorence** [comment]
It seems that the padding is missing in the central merge editor when the padding is at the end of the editor (as shown in example5 here below):
Screenshot from 2023-10-02 14-40-22

**Comment by fcollonval** [comment]
bot please update playwright snapshots

**Comment by fcollonval** [comment]
bot please update playwright snapshots

**Comment by fcollonval** [comment]
bot please update playwright snapshots

**Comment by fcollonval** [comment]
bot please update playwright snapshots

**Pull request closed without merging**
