### PR TITLE
CM6: Fix spacing between editors

### PR DESCRIPTION
**Pull request by HaudinFlorence**
This PR fixes #https://github.com/jupyter/nbdime/issues/720

The gap between the different editors that was put to 10 px has been removed.

**CM5 version**
Screenshot from 2023-10-31 18-23-51

**CM6 version**
Screenshot from 2023-10-31 18-27-02

### CODE REVIEW

**Comment by fcollonval** [comment]
Bot please update playwright snapshots

**Comment by vidartf** [comment]
In the CM6 screenshot there is still a gap (white) between the local and remote editor and the merged result view. We should get rid of that too before closing #720.

**Comment by vidartf** [comment]
(Happy to merge this as it currently is, as it is a good improvement though!)

**Review by vidartf — APPROVED** [review]

**Comment by HaudinFlorence** [comment]
@vidartf I did not see the white remainig spaces. I am proposing a fix for this in commit (not sure that it is the best solution) [c285455](https://github.com/jupyter/nbdime/pull/728/commits/c28545558d43627f8c7e2f6477ba2fa1684d9da8) consisting in adding the cell background color style to the left and right editors (as well as in the central one since I guess it may happen that this white gap occurs in this editor as well).

**Comment by vidartf** [comment]
I think the underlying problem is that the central editor is higher for some reason.  You can see this even with the old spacing. Inspecting this closer in CSS, it seems to be from some remaining border styles being applied:

```css
/* merge.css */
.jp-Notebook-merge .cm-merge-m-chunk-end-either, .jp-Notebook-merge .cm-merge-m-chunk-end-mixed:not(.cm-merge-m-chunk-custom) {
    border-bottom: 1px solid var(--jp-merge-either-color1);
}
```

This one should be switched to whatever (non-space taking) style we are using for the other chunk starts/ends.

**Comment by HaudinFlorence** [comment]
I think that there is a discrepancy between the height of the local and remote editors and the height of the central one. There was also some borders surrounding the editors in the CM5 version that are not present in the current CM6 version.

**Comment by vidartf** [comment]
Bot please update playwright snapshots

**Comment by HaudinFlorence** [comment]
> I think the underlying problem is that the central editor is higher for some reason. You can see this even with the old spacing. Inspecting this closer in CSS, it seems to be from some remaining border styles being applied:
> 
> ```css
> /* merge.css */
> .jp-Notebook-merge .cm-merge-m-chunk-end-either, .jp-Notebook-merge .cm-merge-m-chunk-end-mixed:not(.cm-merge-m-chunk-custom) {
>     border-bottom: 1px solid var(--jp-merge-either-color1);
> }
> ```
> 
> This one should be switched to whatever (non-space taking) style we are using for the other chunk starts/ends.

Sorry. I don't get it.

**Comment by HaudinFlorence** [comment]
> I think the underlying problem is that the central editor is higher for some reason. You can see this even with the old spacing. Inspecting this closer in CSS, it seems to be from some remaining border styles being applied:
> 
> ```css
> /* merge.css */
> .jp-Notebook-merge .cm-merge-m-chunk-end-either, .jp-Notebook-merge .cm-merge-m-chunk-end-mixed:not(.cm-merge-m-chunk-custom) {
>     border-bottom: 1px solid var(--jp-merge-either-color1);
> }
> ```
> 
> This one should be switched to whatever (non-space taking) style we are using for the other chunk starts/ends.

This is normally fixed in commit [90bb3ce](https://github.com/jupyter/nbdime/pull/728/commits/90bb3ce4453d6cbb64fd92e5bf5a1a73a5e8854e)
Screenshot from 2023-11-01 13-45-30

**Comment by HaudinFlorence** [comment]
bot please update snapshots

**Comment by HaudinFlorence** [comment]
> There seems to be a discrepancy between the height of the local and remote editors and the height of the central one. This is due to the fact that the adding or not `chunk-start` and `chunk-end` decorations makes that lines don't all have the same height. There is a cumulative effect. At some point we proposed a logics adding systematically a transparent border but it has been removed during the review. I don't remember why. 
 
After having a look at the css, I have been updated on the changes and got the new logics.

**Comment by HaudinFlorence** [comment]
bot please update snapshots.

**Comment by HaudinFlorence** [comment]
> > There seems to be a discrepancy between the height of the local and remote editors and the height of the central one. This is due to the fact that the adding or not `chunk-start` and `chunk-end` decorations makes that lines don't all have the same height. There is a cumulative effect. At some point we proposed a logics adding systematically a transparent border but it has been removed during the review. I don't remember why.
> 
> After having a look at the css, I have been updated on the changes. But I don't understand where the style of the decoration for the start / end of the chunks is defined now... without using the `border-bottom` / `bottom-top` properties. There are maybe some other leftovers of the old logics remaining (everywhere `border` properties is used). The cyan color has been lost in commit [90bb3ce](https://github.com/jupyter/nbdime/pull/728/commits/90bb3ce4453d6cbb64fd92e5bf5a1a73a5e8854e) for the `chunk-start-mixed`and `chunk-start-end`decorations.

I am now ok with this and this should be fixed with [c2d47fd](https://github.com/jupyter/nbdime/pull/728/commits/c2d47fddecc61fc2874f7cbccafde21609536b84)

**Comment by HaudinFlorence** [comment]
bot please update snapshots

**Comment by HaudinFlorence** [comment]
bot please update snapshots

**Comment by HaudinFlorence** [comment]
> I think you are missing "playwright". We can change the trigger phase (which we did recently elsewhere) to simplify it, but in this repo it is still:
> 
> bot please update playwright snapshots

My bad... Thanks Mike

**Review by krassowski — APPROVED** [review]
Looks good to me, thank you @HaudinFlorence!

**Pull request merged**
