### PR TITLE
Update to use final JupyterLab 2.0 versions

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by telamonian** [comment]
jupyterlab-git needs this pulled in and released before we can finish our 2.0 upgrades (due to a direct dependency on nbdime)

**Comment by vidartf** [comment]
Thanks! I'll run some checks locally, and do a release once I'm satisfied things are working as expected. Will have to figure out the right semvers :)

**Comment by vidartf** [comment]
@telamonian I see that I'm missing the deprecated.css when testing master of nbdime with lab 2.0, so I'm missing some of the CSS based icons (e.g. `var(--jp-icon-caret-up)`). Is this supposed to be included?

**Comment by vidartf** [comment]
Ah, I see the variable name changed spelling in deprecated.css compared to 1.x (`jp-icon-caretup` --> `jp-icon-caret-up`).

**Comment by vidartf** [comment]
@telamonian I'm trying to use `LabIcon` instead, but I keep getting errors along the line of:
```
SVG HTML was malformed for LabIcon instance.
name: ui-components:caret-down, svgstr: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNiIgdmlld0JveD0iMCAwIDE4IDE4Ij4KICA8ZyBjbGFzcz0ianAtaWNvbjMiIGZpbGw9IiM2MTYxNjEiIHNoYXBlLXJlbmRlcmluZz0iZ2VvbWV0cmljUHJlY2lzaW9uIj4KICAgIDxwYXRoIGQ9Ik01LjIsNy41TDksMTEuMmwzLjgtMy44SDUuMnoiLz4KICA8L2c+Cjwvc3ZnPgo=
```

**Comment by vidartf** [comment]
Ah, I see that `LabIcon` now puts requirements on how consumers roll up SVGs. I'll probably roll my own icons then.

**Pull request merged**
