### PR TITLE
Various web improvements

### PR DESCRIPTION
**Pull request by vidartf**
- Clean up paths for static resources.
 - Have diff and merge view start rendering cell widgets as they become ready. Previously, the rendering could be severely delayed from laying out the CodeMirror editors for large notebooks. Some other optimizations were also applied.
 - Improve stylings, particularly of outputs in diff.
 - Refactors renderable models / widgets in preparation for #99.

### CODE REVIEW

**Comment by vidartf** [comment]
Not exactly sure what the CI failure is, as I am not able to reproduce it locally. However, it persisted over a re-run, so we should probably figure it out before merging.

**Comment by vidartf** [comment]
This PR should pass once rebased onto #216. Waiting for that.

**Comment by vidartf** [comment]
Rebased. Had to clear the Travis caches again, but now all green! With #216 merged, I do not think we will have cache issue again for a while (I think the cache might need clearing out after removing dependencies?).

**Comment by minrk** [comment]
If the cache is working properly, it shouldn't ever need clearing. How much time does the cache save?

**Comment by vidartf** [comment]
We cache `node_modules`, which should save quite a bit for the `npm install` step (based on local experience). From Travis timings, it looks like it is >4 min without cache, and >2 min with cache. In principle, the `node_modules` cache should be invalidated when `package.json` changes. I know you can do this with appveyor (but its caches didn't cause any problem now), but have not been able to find the same for Travis.

**Pull request merged**
