### PR TITLE
Add mercurial entry points

### LINKED ISSUE #250: Document integration with mercurial
As far as I can tell, nothing in `nbdime` is git-specific. However, the docs heavily emphasize git. I'd like to add a section explaining how to integrate `nbdime` as an external merge tool with mercurial.

### PR DESCRIPTION
**Pull request by vidartf**
Resolves #250.

### TODO
- [x] Add documentation for mercurial configuration
- [x] Add tests for mercurial entry points.
- [x] Add tests for diff/merge with mixed repos (subdirs + other files changed than just notebooks). I suspect this is still not completely fixed.

### CODE REVIEW

**Comment by vidartf** [comment]
For now, I've been using the following config locally:
```
[extensions]
extdiff =

[extdiff]
cmd.nbdime = hg-nbdiff
cmd.nbdimeweb = hg-nbdiffweb
opts.nbdimeweb = --log-level ERROR
cmd.diffdebug = python
opts.diffdebug = -c "import sys; print(sys.argv)"

[merge-tools]
nbdime.priority = 2
nbdime.premerge = False
nbdime.executable = hg-nbmerge
nbdime.args = $base $local $other $output
nbdime-web.priority = 1
nbdime-web.premerge = False
nbdime-web.executable = hg-nbmergeweb
nbdime-web.args = --log-level ERROR $base $local $other $output
nbdime-web.gui = True

[merge-patterns]
**.ipynb = nbdime

```

**Comment by vidartf** [comment]
All boxes ticked, and all green, so this is ready for review now.

**Comment by ngoldbaum** [comment]
Cool! I will share this in the mercurial community.

**Comment by vidartf** [comment]
@ngoldbaum Neat. Just be aware that it has not been packaged into a release yet.

**Comment by ngoldbaum** [comment]
@vidartf if you're feeling ambitious, it was pointed out to me by a mercurial developer that you could send a patch to mercurial to modify this file:

https://www.mercurial-scm.org/repo/hg/file/tip/mercurial/default.d/mergetools.rc

If you do that, if someone has nbdime installed then they won't need to modify their .hgrc to get it working. I'd be happy to answer questions about contributing to mercurial if you have any.

**Comment by Lothiraldan** [comment]
@vidartf If you need any helps for sending a patch to Mercurial core, let me know, I would be more than happy to help.

**Comment by vidartf** [comment]
Yes, now that this has been released it would be good to look into this. Is it only possible to add config entries for the mergetool, or also diff extensions?

**Pull request merged**
